# Generated by Django 3.1.6 on 2021-02-19 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shareRes', '0002_restaurant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='category_name',
            new_name='category',
        ),
    ]
